FROM node:22

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y pnpm-lock.yaml al directorio de trabajo
COPY package.json pnpm-lock.yaml ./

# Instala pnpm globalmente
RUN npm install -g pnpm

# Instala las dependencias del proyecto
RUN pnpm install

# Copia el resto del código de la aplicación al contenedor
COPY . .

# Construye la aplicación con esbuild
RUN node build.cjs

# Expone el puerto que utiliza la aplicación (ajústalo según sea necesario)
ARG OPEN_API_KEY
ARG PORT

# Comando para ejecutar la aplicación
CMD ["pnpm", "start"]

